services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: socialmedia_app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sm_network
    secrets:
      - db_password

  app:
    image: socialmediaapp:latest
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Postgres: "Host=db;Port=5432;Database=socialmedia_app;Username=postgres;Password="
    ports:
      - "8081:8080"
    networks:
      - sm_network
    secrets:
      - db_password

volumes:
  pgdata:

networks:
  sm_network:
    driver: bridge

secrets:
  db_password:
    file: ./secrets/db_password.txt